package geo.gdal;

public class GdalGlobal_DataFormat {
	/*
	 * data format
	 */
	public static String DATAFORMAT_RASTER_AAIGrid = "AAIGrid"; // Arc/Info ASCII Grid
	public static String DATAFORMAT_RASTER_ACE2 = "ACE2"; // ACE2
	public static String DATAFORMAT_RASTER_ADRG = "ADRG"; // ADRG/ARC Digitized Raster Graphics (.gen/.thf)
	public static String DATAFORMAT_RASTER_AIG = "AIG"; // Arc/Info Binary Grid
	public static String DATAFORMAT_RASTER_AIRSAR = "AIRSAR"; // AIRSAR Polarimetric Format
	public static String DATAFORMAT_RASTER_ARG = "ARG"; // Azavea Raster Grid
	public static String DATAFORMAT_RASTER_BAG = "BAG"; // Bathymetry Attributed Grid
	public static String DATAFORMAT_RASTER_BLX = "BLX"; // Magellan BLX Topo File Format
	public static String DATAFORMAT_RASTER_BMP = "BMP"; // Microsoft Windows Device Independent Bitmap
	public static String DATAFORMAT_RASTER_BPG = "BPG"; // Better Portable Graphics
	public static String DATAFORMAT_RASTER_BSB = "BSB"; // Maptech/NOAA BSB Nautical Chart Format
	public static String DATAFORMAT_RASTER_BT = "BT"; // VTP .bt Binary Terrain Format
	public static String DATAFORMAT_RASTER_BYN = "BYN"; // Natural Resources Canada’s Geoid file format (.byn)
	public static String DATAFORMAT_RASTER_CAD = "CAD"; // AutoCAD DWG raster layer
	public static String DATAFORMAT_RASTER_CALS = "CALS"; // CALS Type 1
	public static String DATAFORMAT_RASTER_CEOS = "CEOS"; // CEOS Image
	public static String DATAFORMAT_RASTER_COASP = "COASP"; // DRDC COASP SAR Processor Raster
	public static String DATAFORMAT_RASTER_COG = "COG"; // Cloud Optimized GeoTIFF generator
	public static String DATAFORMAT_RASTER_COSAR = "COSAR"; // TerraSAR-X Complex SAR Data Product
	public static String DATAFORMAT_RASTER_CPG = "CPG"; // Convair PolGASP data
	public static String DATAFORMAT_RASTER_CTable2 = "CTable2"; // CTable2 Datum Grid Shift
	public static String DATAFORMAT_RASTER_CTG = "CTG"; // USGS LULC Composite Theme Grid
	public static String DATAFORMAT_RASTER_DAAS = "DAAS"; // DAAS (Airbus DS Intelligence Data As A Service driver)
	public static String DATAFORMAT_RASTER_DB2 = "DB2"; // DB2 raster
	public static String DATAFORMAT_RASTER_DDS = "DDS"; // DirectDraw Surface
	public static String DATAFORMAT_RASTER_DERIVED = "DERIVED"; // Derived subdatasets driver
	public static String DATAFORMAT_RASTER_DIMAP = "DIMAP"; // Spot DIMAP
	public static String DATAFORMAT_RASTER_DIPEx = "DIPEx"; // ELAS DIPEx
	public static String DATAFORMAT_RASTER_DODS = "DODS"; // OPeNDAP Grid Client
	public static String DATAFORMAT_RASTER_DOQ1 = "DOQ1"; // First Generation USGS DOQ
	public static String DATAFORMAT_RASTER_DOQ2 = "DOQ2"; // New Labelled USGS DOQ
	public static String DATAFORMAT_RASTER_DTED = "DTED"; // Military Elevation Data
	public static String DATAFORMAT_RASTER_E00GRID = "E00GRID"; // Arc/Info Export E00 GRID
	public static String DATAFORMAT_RASTER_ECRGTOC = "ECRGTOC"; // ECRG Table Of Contents (TOC.xml)
	public static String DATAFORMAT_RASTER_ECW = "ECW"; // Enhanced Compressed Wavelets (.ecw)
	public static String DATAFORMAT_RASTER_EEDAI = "EEDAI"; // Google Earth Engine Data API Image
	public static String DATAFORMAT_RASTER_EHdr = "EHdr"; // ESRI .hdr Labelled
	public static String DATAFORMAT_RASTER_EIR = "EIR"; // Erdas Imagine Raw
	public static String DATAFORMAT_RASTER_ELAS = "ELAS"; // Earth Resources Laboratory Applications Software
	public static String DATAFORMAT_RASTER_ENVI = "ENVI"; // ENVI .hdr Labelled Raster
	public static String DATAFORMAT_RASTER_EPSILON = "EPSILON"; // Wavelet compressed images
	public static String DATAFORMAT_RASTER_ERS = "ERS"; // ERMapper .ERS
	public static String DATAFORMAT_RASTER_ESAT = "ESAT"; // Envisat Image Product
	public static String DATAFORMAT_RASTER_FAST = "FAST"; // EOSAT FAST Format
	public static String DATAFORMAT_RASTER_FIT = "FIT"; // FIT
	public static String DATAFORMAT_RASTER_FITS = "FITS"; // Flexible Image Transport System
	public static String DATAFORMAT_RASTER_FujiBAS = "FujiBAS"; // Fuji BAS Scanner Image
	public static String DATAFORMAT_RASTER_GenBin = "GenBin"; // Generic Binary (.hdr labelled)
	public static String DATAFORMAT_RASTER_GeoRaster = "GeoRaster"; // Oracle Spatial GeoRaster
	public static String DATAFORMAT_RASTER_GFF = "GFF"; // Sandia National Laboratories GSAT File Format
	public static String DATAFORMAT_RASTER_GIF = "GIF"; // Graphics Interchange Format
	public static String DATAFORMAT_RASTER_GMT = "GMT"; // GMT Compatible netCDF
	public static String DATAFORMAT_RASTER_GPKG = "GPKG"; // GeoPackage raster
	public static String DATAFORMAT_RASTER_GRASS = "GRASS"; // GRASS Raster Format
	public static String DATAFORMAT_RASTER_GRASSASCIIGrid = "GRASSASCIIGrid"; // GRASS ASCII Grid
	public static String DATAFORMAT_RASTER_GRIB = "GRIB"; // WMO General Regularly-distributed Information in Binary  form
	public static String DATAFORMAT_RASTER_GS7BG = "GS7BG"; // Golden Software Surfer 7 Binary Grid File Format
	public static String DATAFORMAT_RASTER_GSAG = "GSAG"; // Golden Software ASCII Grid File Format
	public static String DATAFORMAT_RASTER_GSBG = "GSBG"; // Golden Software Binary Grid File Format
	public static String DATAFORMAT_RASTER_GSC = "GSC"; // GSC Geogrid
	public static String DATAFORMAT_RASTER_GTA = "GTA"; // Generic Tagged Arrays
	public static String DATAFORMAT_RASTER_GTiff = "GTiff"; // GeoTIFF File Format
	public static String DATAFORMAT_RASTER_GXF = "GXF"; // Grid eXchange File
	public static String DATAFORMAT_RASTER_HDF4 = "HDF4"; // Hierarchical Data Format Release 4 (HDF4)
	public static String DATAFORMAT_RASTER_HDF4Image = "HDF4Image"; // Hierarchical Data Format Release 4 (HDF4)
	public static String DATAFORMAT_RASTER_HDF5 = "HDF5"; // Hierarchical Data Format Release 5 (HDF5)
	public static String DATAFORMAT_RASTER_HDF5Image = "HDF5Image"; // Hierarchical Data Format Release 5 (HDF5)
	public static String DATAFORMAT_RASTER_HF2 = "HF2"; // HF2/HFZ heightfield raster
	public static String DATAFORMAT_RASTER_HFA = "HFA"; // Erdas Imagine .img
	public static String DATAFORMAT_RASTER_IDA = "IDA"; // Image Display and Analysis
	public static String DATAFORMAT_RASTER_RST = "RST"; // Idrisi Raster Format
	public static String DATAFORMAT_RASTER_IGNFHeightASCIIGrid = "IGNFHeightASCIIGrid"; // IGN-France height correction ASCII grids
	public static String DATAFORMAT_RASTER_ILWIS = "ILWIS"; // Raster Map
	public static String DATAFORMAT_RASTER_INGR = "INGR"; // Intergraph Raster Format
	public static String DATAFORMAT_RASTER_IRIS = "IRIS"; // Vaisala’s weather radar software format
	public static String DATAFORMAT_RASTER_ISCE = "ISCE"; // ISCE
	public static String DATAFORMAT_RASTER_ISIS2 = "ISIS2"; // USGS Astrogeology ISIS Cube (Version 2)
	public static String DATAFORMAT_RASTER_ISIS3 = "ISIS3"; // USGS Astrogeology ISIS Cube (Version 3)
	public static String DATAFORMAT_RASTER_JDEM = "JDEM"; // Japanese DEM (.mem)
	public static String DATAFORMAT_RASTER_JP2ECW = "JP2ECW"; // ERDAS JPEG2000 (.jp2)
	public static String DATAFORMAT_RASTER_JP2KAK = "JP2KAK"; // JPEG-2000 (based on Kakadu)
	public static String DATAFORMAT_RASTER_JP2LURA = "JP2LURA"; // JPEG2000 driver based on Lurawave library
	public static String DATAFORMAT_RASTER_JP2MrSID = "JP2MrSID"; // JPEG2000 via MrSID SDK
	public static String DATAFORMAT_RASTER_JP2OpenJPEG = "JP2OpenJPEG"; // JPEG2000 driver based on OpenJPEG library
	public static String DATAFORMAT_RASTER_JPEG = "JPEG"; // JPEG JFIF File Format
	public static String DATAFORMAT_RASTER_JPEG2000 = "JPEG2000"; // Implementation of the JPEG-2000 part 1
	public static String DATAFORMAT_RASTER_JPEGLS = "JPEGLS"; // JPEGLS
	public static String DATAFORMAT_RASTER_JPIPKAK = "JPIPKAK"; // JPIP Streaming
	public static String DATAFORMAT_RASTER_KEA = "KEA"; // KEA
	public static String DATAFORMAT_RASTER_KMLSuperoverlay = "KMLSuperoverlay"; // KMLSuperoverlay
	public static String DATAFORMAT_RASTER_KRO = "KRO"; // KOLOR Raw format
	public static String DATAFORMAT_RASTER_L1B = "L1B"; // NOAA Polar Orbiter Level 1b Data Set (AVHRR)
	public static String DATAFORMAT_RASTER_LAN = "LAN"; // Erdas 7.x .LAN and .GIS
	public static String DATAFORMAT_RASTER_LCP = "LCP"; // FARSITE v.4 LCP Format
	public static String DATAFORMAT_RASTER_Leveller = "Leveller"; // Daylon Leveller Heightfield
	public static String DATAFORMAT_RASTER_LOSLAS = "LOSLAS"; // NADCON .los/.las Datum Grid Shift
	public static String DATAFORMAT_RASTER_MAP = "MAP"; // OziExplorer .MAP
	public static String DATAFORMAT_RASTER_MRF = "MRF"; // Meta Raster Format
	public static String DATAFORMAT_RASTER_MBTiles = "MBTiles"; // MBTiles
	public static String DATAFORMAT_RASTER_MEM = "MEM"; // In Memory Raster
	public static String DATAFORMAT_RASTER_MFF = "MFF"; // Vexcel MFF Raster
	public static String DATAFORMAT_RASTER_MFF2 = "MFF2"; // Vexcel MFF2 Image
	public static String DATAFORMAT_RASTER_MG4Lidar = "MG4Lidar"; // MrSID/MG4 LiDAR Compression / Point Cloud View
																	// files
	public static String DATAFORMAT_RASTER_MrSID = "MrSID"; // Multi-resolution Seamless Image Database
	public static String DATAFORMAT_RASTER_MSG = "MSG"; // Meteosat Second Generation
	public static String DATAFORMAT_RASTER_MSGN = "MSGN"; // Meteosat Second Generation (MSG) Native Archive Format
															// (.nat)
	public static String DATAFORMAT_RASTER_NDF = "NDF"; // NLAPS Data Format
	public static String DATAFORMAT_RASTER_netCDF = "netCDF"; // NetCDF: Network Common Data Form
	public static String DATAFORMAT_RASTER_NGSGEOID = "NGSGEOID"; // NOAA NGS Geoid Height Grids
	public static String DATAFORMAT_RASTER_NGW = "NGW"; // NextGIS Web
	public static String DATAFORMAT_RASTER_NITF = "NITF"; // National Imagery Transmission Format
	public static String DATAFORMAT_RASTER_NTv1 = "NTv1"; // NTv1 Datum Grid Shift
	public static String DATAFORMAT_RASTER_NTv2 = "NTv2"; // NTv2 Datum Grid Shift
	public static String DATAFORMAT_RASTER_NWT_GRD = "NWT_GRD"; // Northwood/Vertical Mapper File Format
	public static String DATAFORMAT_RASTER_NWT_GRC = "NWT_GRC"; // Northwood/Vertical Mapper File Format
	public static String DATAFORMAT_RASTER_OZI = "OZI"; // OZF2/OZFX3 raster
	public static String DATAFORMAT_RASTER_JAXAPALSAR = "JAXAPALSAR"; // JAXA PALSAR Processed Products
	public static String DATAFORMAT_RASTER_PAux = "PAux"; // PCI .aux Labelled Raw Format
	public static String DATAFORMAT_RASTER_PCIDSK = "PCIDSK"; // PCI Geomatics Database File
	public static String DATAFORMAT_RASTER_PCRaster = "PCRaster"; // PCRaster raster file format
	public static String DATAFORMAT_RASTER_PDF = "PDF"; // Geospatial PDF
	public static String DATAFORMAT_RASTER_PDS = "PDS"; // Planetary Data System v3
	public static String DATAFORMAT_RASTER_PDS4 = "PDS4"; // NASA Planetary Data System (Version 4)
	public static String DATAFORMAT_RASTER_PLMosaic = "PLMosaic"; // PLMosaic (Planet Labs Mosaics API)
	public static String DATAFORMAT_RASTER_PNG = "PNG"; // Portable Network Graphics
	public static String DATAFORMAT_RASTER_PNM = "PNM"; // Netpbm (.pgm, .ppm)
	public static String DATAFORMAT_RASTER_PostGISRaster = "PostGISRaster"; // PostGIS Raster driver
	public static String DATAFORMAT_RASTER_PRF = "PRF"; // PHOTOMOD Raster File
	public static String DATAFORMAT_RASTER_R = "R"; // R Object Data Store
	public static String DATAFORMAT_RASTER_Rasdaman = "Rasdaman"; // Rasdaman GDAL driver
	public static String DATAFORMAT_RASTER_Rasterlite = "Rasterlite"; // Rasters in SQLite DB
	public static String DATAFORMAT_RASTER_SQLite = "SQLite"; // Rasters in SQLite DB
	public static String DATAFORMAT_RASTER_RDA = "RDA"; // RDA (DigitalGlobe Raster Data Access)
	public static String DATAFORMAT_RASTER_RDB = "RDB"; // RIEGL Database
	public static String DATAFORMAT_RASTER_RIK = "RIK"; // Swedish Grid Maps
	public static String DATAFORMAT_RASTER_RMF = "RMF"; // Raster Matrix Format
	public static String DATAFORMAT_RASTER_ROI_PAC = "ROI_PAC"; // ROI_PAC
	public static String DATAFORMAT_RASTER_RPFTOC = "RPFTOC"; // Raster Product Format/RPF (a.toc)
	public static String DATAFORMAT_RASTER_RRASTER = "RRASTER"; // R Raster
	public static String DATAFORMAT_RASTER_RS2 = "RS2"; // RadarSat 2 XML Product
	public static String DATAFORMAT_RASTER_SAFE = "SAFE"; // Sentinel-1 SAFE XML Product
	public static String DATAFORMAT_RASTER_SAR_CEOS = "SAR_CEOS"; // CEOS SAR Image
	public static String DATAFORMAT_RASTER_SAGA = "SAGA"; // SAGA GIS Binary Grid File Format
	public static String DATAFORMAT_RASTER_SDE = "SDE"; // ESRI ArcSDE Raster
	public static String DATAFORMAT_RASTER_SDTS = "SDTS"; // USGS SDTS DEM
	public static String DATAFORMAT_RASTER_SENTINEL2 = "SENTINEL2"; // Sentinel-2 Products
	public static String DATAFORMAT_RASTER_SGI = "SGI"; // SGI Image Format
	public static String DATAFORMAT_RASTER_SIGDEM = "SIGDEM"; // Scaled Integer Gridded DEM
	public static String DATAFORMAT_RASTER_SNODAS = "SNODAS"; // Snow Data Assimilation System
	public static String DATAFORMAT_RASTER_SRP = "SRP"; // Standard Product Format (ASRP/USRP) (.gen)
	public static String DATAFORMAT_RASTER_SRTMHGT = "SRTMHGT"; // SRTM HGT Format
	public static String DATAFORMAT_RASTER_Terragen = "Terragen"; // Terragen™ Terrain File
	public static String DATAFORMAT_RASTER_TIL = "TIL"; // EarthWatch/DigitalGlobe .TIL
	public static String DATAFORMAT_RASTER_TileDB = "TileDB"; // TileDB
	public static String DATAFORMAT_RASTER_TSX = "TSX"; // TerraSAR-X Product
	public static String DATAFORMAT_RASTER_USGSDEM = "USGSDEM"; // USGS ASCII DEM (and CDED)
	public static String DATAFORMAT_RASTER_VICAR = "VICAR"; // VICAR
	public static String DATAFORMAT_RASTER_VRT = "VRT"; // GDAL Virtual Format
	public static String DATAFORMAT_RASTER_WCS = "WCS"; // OGC Web Coverage Service
	public static String DATAFORMAT_RASTER_WEBP = "WEBP"; // WEBP
	public static String DATAFORMAT_RASTER_WMS = "WMS"; // Web Map Services
	public static String DATAFORMAT_RASTER_WMTS = "WMTS"; // OGC Web Map Tile Service
	public static String DATAFORMAT_RASTER_XPM = "XPM"; // X11 Pixmap
	public static String DATAFORMAT_RASTER_XYZ = "XYZ"; // ASCII Gridded XYZ
	public static String DATAFORMAT_RASTER_ZMAP = "ZMAP"; // ZMap Plus Grid

	/*
	 * vector format
	 */
	public static String DATAFORMAT_VECTOR_AERONAVFAA = "AERONAVFAA"; // Aeronav FAA
	public static String DATAFORMAT_VECTOR_AmigoCloud = "AmigoCloud"; // AmigoCloud
	public static String DATAFORMAT_VECTOR_AO = "AO"; // ESRI ArcObjects
	public static String DATAFORMAT_VECTOR_ARCGEN = "ARCGEN"; // Arc/Info Generate
	public static String DATAFORMAT_VECTOR_AVCBIN = "AVCBIN"; // Arc/Info Binary Coverage
	public static String DATAFORMAT_VECTOR_AVCE00 = "AVCE00"; // Arc/Info E00 (ASCII) Coverage
	public static String DATAFORMAT_VECTOR_BNA = "BNA"; // Atlas BNA
	public static String DATAFORMAT_VECTOR_CAD = "CAD"; // AutoCAD DWG
	public static String DATAFORMAT_VECTOR_CARTO = "CARTO"; // Carto
	public static String DATAFORMAT_VECTOR_Cloudant = "Cloudant"; // Cloudant
	public static String DATAFORMAT_VECTOR_CouchDB = "CouchDB"; // CouchDB/GeoCouch
	public static String DATAFORMAT_VECTOR_CSV = "CSV"; // Comma Separated Value (.csv)
	public static String DATAFORMAT_VECTOR_CSW = "CSW"; // OGC CSW (Catalog Service for the Web)
	public static String DATAFORMAT_VECTOR_DB2 = "DB2"; // DB2 Spatial
	public static String DATAFORMAT_VECTOR_DGN = "DGN"; // Microstation DGN
	public static String DATAFORMAT_VECTOR_DGNv8 = "DGNv8"; // Microstation DGN v8
	public static String DATAFORMAT_VECTOR_DODS = "DODS"; // DODS/OPeNDAP
	public static String DATAFORMAT_VECTOR_DWG = "DWG"; // AutoCAD DWG
	public static String DATAFORMAT_VECTOR_DXF = "DXF"; // AutoCAD DXF
	public static String DATAFORMAT_VECTOR_EDIGEO = "EDIGEO"; // EDIGEO
	public static String DATAFORMAT_VECTOR_EEDA = "EEDA"; // Google Earth Engine Data API
	public static String DATAFORMAT_VECTOR_ElasticSearch = "ElasticSearch"; // ElasticSearch: Geographically Encoded  Objects for ElasticSearch
	public static String DATAFORMAT_VECTOR_ESRIJSON = "ESRIJSON"; // ESRIJSON / FeatureService driver
	public static String DATAFORMAT_VECTOR_FileGDB = "FileGDB"; // ESRI File Geodatabase (FileGDB)
	public static String DATAFORMAT_VECTOR_FlatGeobuf = "FlatGeobuf"; // FlatGeobuf
	public static String DATAFORMAT_VECTOR_FME = "FME"; // FMEObjects Gateway
	public static String DATAFORMAT_VECTOR_Geoconcept = "Geoconcept"; // GeoConcept text export
	public static String DATAFORMAT_VECTOR_GeoJSON = "GeoJSON"; // GeoJSON
	public static String DATAFORMAT_VECTOR_GeoJSONSeq = "GeoJSONSeq"; // GeoJSONSeq: sequence of GeoJSON features
	public static String DATAFORMAT_VECTOR_Geomedia = "Geomedia"; // Geomedia MDB database
	public static String DATAFORMAT_VECTOR_GeoRSS = "GeoRSS"; // GeoRSS : Geographically Encoded Objects for RSS feeds
	public static String DATAFORMAT_VECTOR_GFT = "GFT"; // Google Fusion Tables
	public static String DATAFORMAT_VECTOR_GML = "GML"; // Geography Markup Language
	public static String DATAFORMAT_VECTOR_GMLAS = "GMLAS"; // Geography Markup Language (GML) driven by application  schemas
	public static String DATAFORMAT_VECTOR_GMT = "GMT"; // GMT ASCII Vectors (.gmt)
	public static String DATAFORMAT_VECTOR_GPKG = "GPKG"; // GeoPackage vector
	public static String DATAFORMAT_VECTOR_GPSBabel = "GPSBabel"; // GPSBabel
	public static String DATAFORMAT_VECTOR_GPX = "GPX"; // GPS Exchange Format
	public static String DATAFORMAT_VECTOR_GRASS = "GRASS"; // GRASS Vector Format
	public static String DATAFORMAT_VECTOR_GTM = "GTM"; // GPS TrackMaker
	public static String DATAFORMAT_VECTOR_HTF = "HTF"; // Hydrographic Transfer Format
	public static String DATAFORMAT_VECTOR_IDB = "IDB"; // IDB
	public static String DATAFORMAT_VECTOR_IDRISI = "IDRISI"; // Idrisi Vector (.VCT)
	public static String DATAFORMAT_VECTOR_INTERLIS1 = "INTERLIS 1"; // “INTERLIS 1” and “INTERLIS 2” drivers
	public static String DATAFORMAT_VECTOR_INTERLIS2 = "INTERLIS 2"; // “INTERLIS 1” and “INTERLIS 2” drivers
	public static String DATAFORMAT_VECTOR_INGRES = "INGRES"; // INGRES
	public static String DATAFORMAT_VECTOR_JML = "JML"; // JML: OpenJUMP JML format
	public static String DATAFORMAT_VECTOR_KML = "KML"; // Keyhole Markup Language
	public static String DATAFORMAT_VECTOR_LIBKML = "LIBKML"; // LIBKML Driver (.kml .kmz)
	public static String DATAFORMAT_VECTOR_MDB = "MDB"; // Access MDB databases
	public static String DATAFORMAT_VECTOR_Memory = "Memory"; // Memory
	public static String DATAFORMAT_VECTOR_MITAB = "MITAB"; // MapInfo TAB and MIF/MID
	public static String DATAFORMAT_VECTOR_MongoDB = "MongoDB"; // MongoDB
	public static String DATAFORMAT_VECTOR_MongoDBv3 = "MongoDBv3"; // MongoDBv3
	public static String DATAFORMAT_VECTOR_MSSQLSpatial = "MSSQLSpatial"; // Microsoft SQL Server Spatial Database
	public static String DATAFORMAT_VECTOR_MVT = "MVT"; // MVT: Mapbox Vector Tiles
	public static String DATAFORMAT_VECTOR_MySQL = "MySQL"; // MySQL
	public static String DATAFORMAT_VECTOR_NAS = "NAS"; // ALKIS
	public static String DATAFORMAT_VECTOR_netCDF = "netCDF"; // Vector
	public static String DATAFORMAT_VECTOR_NGW = "NGW"; // NextGIS Web
	public static String DATAFORMAT_VECTOR_UKNTF = "UK .NTF"; // UK .NTF
	public static String DATAFORMAT_VECTOR_OAPIF = "OAPIF"; // OGC API - Features
	public static String DATAFORMAT_VECTOR_OCI = "OCI"; // Oracle Spatial
	public static String DATAFORMAT_VECTOR_ODBC = "ODBC"; // ODBC RDBMS
	public static String DATAFORMAT_VECTOR_ODS = "ODS"; // Open Document Spreadsheet
	public static String DATAFORMAT_VECTOR_OGDI = "OGDI"; // OGDI Vectors
	public static String DATAFORMAT_VECTOR_OpenAir = "OpenAir"; // OpenAir Special Use Airspace Format
	public static String DATAFORMAT_VECTOR_OpenFileGDB = "OpenFileGDB"; // ESRI File Geodatabase (OpenFileGDB)
	public static String DATAFORMAT_VECTOR_OSM = "OSM"; // OpenStreetMap XML and PBF
	public static String DATAFORMAT_VECTOR_PDF = "PDF"; // Geospatial PDF
	public static String DATAFORMAT_VECTOR_PDS = "PDS"; // Planetary Data Systems TABLE
	public static String DATAFORMAT_VECTOR_PostgreSQL = "PostgreSQL"; // PostgreSQL / PostGIS
	public static String DATAFORMAT_VECTOR_PGDump = "PGDump"; // PostgreSQL SQL Dump
	public static String DATAFORMAT_VECTOR_PGeo = "PGeo"; // ESRI Personal GeoDatabase
	public static String DATAFORMAT_VECTOR_PLScenes = "PLScenes"; // PLScenes (Planet Labs Scenes/Catalog API)
	public static String DATAFORMAT_VECTOR_S57 = "S57"; // IHO S-57 (ENC)
	public static String DATAFORMAT_VECTOR_SDE = "SDE"; // ESRI ArcSDE
	public static String DATAFORMAT_VECTOR_SDTS = "SDTS"; // SDTS
	public static String DATAFORMAT_VECTOR_SEGUKOOA = "SEGUKOOA"; // SEG-P1 / UKOOA P1/90
	public static String DATAFORMAT_VECTOR_SEGY = "SEGY"; // SEG-Y / SEGY
	public static String DATAFORMAT_VECTOR_Selafin = "Selafin"; // Selafin files
	public static String DATAFORMAT_VECTOR_ESRIShapefile = "\"ESRI Shapefile\""; // ESRI Shapefile / DBF
	public static String DATAFORMAT_VECTOR_SOSI = "SOSI"; // Norwegian SOSI Standard
	public static String DATAFORMAT_VECTOR_SQLite = "SQLite"; // SQLite / Spatialite RDBMS
	public static String DATAFORMAT_VECTOR_SUA = "SUA"; // Tim Newport-Peace’s Special Use Airspace Format
	public static String DATAFORMAT_VECTOR_SVG = "SVG"; // Scalable Vector Graphics
	public static String DATAFORMAT_VECTOR_SXF = "SXF"; // SXF
	public static String DATAFORMAT_VECTOR_TIGER = "TIGER"; // U.S. Census TIGER/Line
	public static String DATAFORMAT_VECTOR_TopoJSON = "TopoJSON"; // TopoJSON driver
	public static String DATAFORMAT_VECTOR_VDV = "VDV"; // VDV-451/VDV-452/INTREST Data Format
	public static String DATAFORMAT_VECTOR_VFK = "VFK"; // Czech Cadastral Exchange Data Format
	public static String DATAFORMAT_VECTOR_VRT = "VRT"; // Virtual Format
	public static String DATAFORMAT_VECTOR_Walk = "Walk"; // Walk Spatial Data
	public static String DATAFORMAT_VECTOR_WAsP = "WAsP"; // WAsP .map format
	public static String DATAFORMAT_VECTOR_WFS = "WFS"; // OGC WFS service
	public static String DATAFORMAT_VECTOR_XLS = "XLS"; // MS Excel format
	public static String DATAFORMAT_VECTOR_XLSX = "XLSX"; // MS Office Open XML spreadsheet
	public static String DATAFORMAT_VECTOR_XPlane = "XPlane"; // X-Plane/Flightgear aeronautical data
}
